FROM python:3.9-slim


WORKDIR /app


COPY recommendation-service/requirements.txt .


RUN pip install --no-cache-dir --user -r requirements.txt

COPY recommendation-service/ . 


RUN chmod +x /app


ENV PATH="/home/python/.local/bin:${PATH}"
ENV PYTHONPATH="/home/python/.local/lib/python3.9/site-packages"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]