FROM node:18-alpine

WORKDIR /app
COPY e-commerce-master/package*.json ./
RUN npm ci --only=production

COPY e-commerce-master/. .
RUN npm run build

EXPOSE 3000 3002 3003 3005
CMD ["node", "dist/apps/e-commerce/main"]