FROM node:18-alpine AS builder

RUN npm install -g pnpm
WORKDIR /app
COPY e-commerce-master/package.json e-commerce-master/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY e-commerce-master/. .
RUN pnpm run build
RUN pnpm install --prod --frozen-lockfile

EXPOSE 3000
CMD ["node", "dist/apps/e-commerce/main"]