# File: kaniko.yaml (Updated for debugging)
apiVersion: v1
kind: Pod
metadata:
  name: test-kaniko-pod-debug # Unique name for this test pod
  namespace: jenkins   # Must match your Jenkins namespace
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2
    imagePullPolicy: IfNotPresent
    # Use busybox shell to run a long sleep loop
    command: ["/busybox/sh", "-c", "--"]
    args: ["echo 'Kaniko container started'; while true; do echo 'Sleeping...'; sleep 30; done"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
  - name: jnlp # Jenkins Agent Container
    image: jenkins/inbound-agent:jdk11
    imagePullPolicy: IfNotPresent
    # Keep this one alive with sleep too for easy debugging
    command: ["sleep"]
    args: ["3600"] # Sleep for 1 hour
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  volumes:
  - name: workspace
    emptyDir: {}