apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/e-shop-deploy/e-shop-repo/ecommerce-frontend:latest
        ports:
        - containerPort: 80