apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: ecommerce-backend-sa
      volumes:
        - name: secrets-script-volume
          emptyDir: {}
      initContainers:
        - name: fetch-secrets
          image: google/cloud-sdk:alpine
          command: ['/bin/sh', '-c']
          env:
            - name: DB_PASSWORD_SECRET_NAME
              value: "ecommerce-db-password"
            - name: DB_CONNECTION_NAME_SECRET_NAME
              value: "ecommerce-db-connection-name"
            - name: JWT_SECRET_NAME
              value: "ecommerce-jwt-secret"
            # Add other relevant secrets for product service
          args:
            - |
              set -eu
              SCRIPT_PATH="/mnt/secrets-fetched/secrets.env"
              echo "# Fetched secrets script for product-service" > $SCRIPT_PATH

              fetch_secret() {
                local secret_name=$1
                local env_var_name=$2
                echo "Fetching secret: $secret_name"
                secret_value=$(gcloud secrets versions access latest --secret=$secret_name)
                escaped_secret_value=$(printf '%s\n' "$secret_value" | sed "s/'/'\\\\''/g")
                echo "export $env_var_name='$escaped_secret_value'" >> $SCRIPT_PATH
              }

              fetch_secret "$DB_PASSWORD_SECRET_NAME" "DB_PASSWORD"
              fetch_secret "$DB_CONNECTION_NAME_SECRET_NAME" "DB_CONNECTION_NAME"
              fetch_secret "$JWT_SECRET_NAME" "JWT_SECRET"
              # Fetch others for product service...

              echo "Product service secrets script created at $SCRIPT_PATH"
          volumeMounts:
            - name: secrets-script-volume
              mountPath: /mnt/secrets-fetched
      containers:
        - name: product
          image: europe-west1-docker.pkg.dev/e-shop-deploy/e-shop-repo/product-service:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              if [ -f /mnt/secrets-fetched/secrets.env ]; then
                echo "Sourcing secrets for product-service"
                . /mnt/secrets-fetched/secrets.env
              else
                echo "Error: Product service secrets script not found!" >&2
                exit 1
              fi
              exec node dist/apps/product/main
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: secrets-script-volume
              mountPath: /mnt/secrets-fetched
          env:
            - name: DB_HOST
              value: "35.240.49.17"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "appuser"
            - name: DB_PRODUCT_NAME
              value: ""
            - name: DB_PASSWORD
              value: ""
            - name: JWT_SECRET
              value: ""
            # - name: DB_CONNECTION_NAME
            #   value: ""