apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
    spec:
      containers:
      - name: api
        image: europe-west1-docker.pkg.dev/e-shop-deploy/e-shop-repo/recommendation-api:latest
        ports:
        - containerPort: 8001