FROM node:18-alpine AS builder

WORKDIR /app
COPY e-commerce-front-master/package*.json ./
RUN npm ci

COPY e-commerce-front-master/. .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/e-commerce-front-master/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]