apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3002 # Port exposed by the Service
      targetPort: 3002 # Port the container listens on
  type: LoadBalancer # Or ClusterIP if internal only